name: Cypress tests
on: push
jobs:
  Cypress_run :
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests 
        run: npx cypress run --record --spec cypress/e2e/hackathon --key 4b574345-4c3b-4af9-a8a7-320b1dfb684c
          

    
      